Repository CuBoulder/express, pull requests merged in 2018-05, with the labels that each got.

#2315 Uncommenting content_editor variables for external invites
  modules/custom/cu_core/cu_core.install
Labels: priority:Critical

#2309 Feature/2284 Remove brokaw, mortone, wetu1300, linebarg from site_owner
  modules/custom/cu_core/cu_core.install
Labels: priority:Critical

#2232 Feature/2079 Update cu_social_media_bundle roles/permissions for 2.9.0.
  modules/custom/cu_social_media_bundle/cu_social_media_bundle.module
Labels: priority:Critical

#2233 Feature/2069 Update cu_feeds_bundle roles perms for 2.9.0 (cu_rss and cu_rss_block ar…
  modules/custom/cu_rss/cu_rss.module
  modules/custom/cu_rss_block/cu_rss_block.module
Labels: priority:Critical

#2320 removed options ffrom exposed filter list
  modules/custom/express_permissions/express_permissions.module
Labels: priority:Critical

#2341 Feature/2066 cu_photo_gallery_bundle updated permissions for 2.9.0 release.
  modules/custom/cu_photo_gallery_bundle/cu_photo_gallery_bundle.install
  modules/custom/cu_photo_gallery_bundle/cu_photo_gallery_bundle.module
Labels: priority:Critical

#2234 Feature/2066 Update cu_photo_gallery_bundle roles/perms.
  modules/custom/cu_photo_gallery_bundle/cu_photo_gallery_bundle.install
  modules/custom/cu_photo_gallery_bundle/cu_photo_gallery_bundle.module
Labels: priority:Critical

#2366 Issue #2365: Update cu_wysiwyg Shortcode Feature
  modules/features/cu_wysiwyg/cu_wysiwyg.module
Labels: priority:Critical, type:Bug

#2394 removing osr-site-owner from being displayed after user exceeds max n…
  modules/custom/express_permissions/express_permissions.module
Labels: type:Bug
